### PR TITLE
Enhancement: Add toast notifications for error and success messages

### LINKED ISSUE #506: Enhance User Experience: Display Error Messages as Popups or Toast Notifications
Currently, error messages during registration/login are displayed below the button, which can sometimes be missed by the user. Also, the error message is not specific. We could also have a toast message for success message for few seconds before moving to a different page.

**Suggested Solution**
I propose using toast notifications or popups to display error and success messages. These should:

- Be visually prominent and easily noticeable.
- Automatically disappear after a short duration (e.g., 3–5 seconds) but allow manual dismissal for user convenience.
- Be consistent with the application's design language and style.

**Alternative**
- Improving the visibility of inline messages (e.g., better styling).
- Using modal dialogs for all messages (but this could interrupt user workflows).

**Additional context**
If this change is agreed upon, I’d be happy to help implement it. @vinsdragonis  Let me know your thoughts!

### PR DESCRIPTION
**Pull request by swati082001**
### Description
This PR adds toast notifications for error and success messages to enhance user experience.

### Changes
- Implemented toast notifications for error and success events.
- Replaced static messages with dynamic popups.

## Register Page
Screenshot 2024-12-03 112309
Screenshot 2024-12-03 112119

## Login Page
Screenshot 2024-12-03 112142
Screenshot 2024-12-03 112207

### Linked Issue
Closes #506

### CODE REVIEW

**Review by vinsdragonis — APPROVED** [review]

**Comment by vinsdragonis** [comment]
The checks have passed, so **I will merge this**. However, a **package version** seems to conflict with the **main** branch. I would request you make the necessary changes before I merge this request.

**Comment by swati082001** [comment]
@vinsdragonis I have removed the package-lock file. Could you please try again?

**Comment by vinsdragonis** [comment]
I guess you need to update the packages rather than remove package.json at this point. Only then can the PR be merged.

**Comment by swati082001** [comment]
@vinsdragonis I hope its all clear now.

**Pull request merged**
