### PR TITLE
Added Hamburger on Mobile

### PR DESCRIPTION
**Pull request by vikashjajra**
### Changes Made So far
1. Added hamburger functionality on smaller devices
2. Added responsiveness to posts section on the homepage

### CODE REVIEW

**Comment by vinsdragonis** [comment]
The content of the posts seems to be more than the screen width. Could you try to make that responsive as well?

**Comment by vikashjajra** [comment]
> The content of the posts seems to be more than the screen width. Could you try to make that responsive as well?

Sure,will look into it on Monday.

**Comment by vinsdragonis** [comment]
I have rectified that part myself. So it's okay.
Thanks for the contribution.

**Comment by vikashjajra** [comment]
> I have rectified that part myself. So it's okay.
> Thanks for the contribution.

Awesome!
Will see if I can contribute more to this project.

**Pull request merged**
