### PR TITLE
User profile page UI complete

### PR DESCRIPTION
**Pull request by Sam-Takahashi**
Styled the user profile page. It now displays user-created posts with pagination(posts per page default 3), and below this, also displays posts created by other users.

### CODE REVIEW

**Comment by Sam-Takahashi** [comment]
Not mobile responsive, due to the design not yet approved and time constraints.

**Comment by vinsdragonis** [comment]
Please mention the corresponding issue number.
Thanks.

**Comment by vinsdragonis** [comment]
There seems to be a few conflicts with `api/package-lock.json`, `client/package-lock.json` and `client/src/components/posts/Posts.jsx`.
Please try to resolve them. Once the merge conflicts have been taken care of, I have no problems approving it.

**Review by vinsdragonis — CHANGES_REQUESTED** [review]
There seem to be a few conflicts with `api/package-lock.json`, `client/package-lock.json` and `client/src/components/posts/Posts.jsx`.
Please restore the `package-lock.json files` in both directories, as not having them can lead to several problems while deploying. Once the merge conflicts have been resolved, I have no problems approving it.

**Comment by Sam-Takahashi** [comment]
Understood.
Found a bug with pagination, after fixing this and the other conflict I'll PR.

**Pull request closed without merging**
